#+TITLE: solar- system-1.1.1-win-0.1发布
#+AUTHOR: Gu Weigang
#+EMAIL: guweigang@outlook.com
#+DATE: 2010-06-24 Thu
#+URI: /blog/2010/06/24/solar-system-1_1_1-win-0_1-release/
#+KEYWORDS: 
#+TAGS: solar, solar win, solarphp
#+LANGUAGE: zh_CN
#+OPTIONS: H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 

下载地址：[[http://solarphp.cn/download/solar-system-1.1.1-win-0.1.rar][http://solarphp.cn/download/solar-system-1.1.1-win-0.1.rar]]

当 然，你总是可以从这里下载最新的版本：[[http://solarphp.cn/download/solar-system-1.1.1-win-latest.rar][http://solarphp.cn/download/solar-system-1.1.1-win-latest.rar]]

Release Note
============
This version for windows is made based on solar 1.1.1(the latest released package).It is improved obviously.

I have tested it with php 5.2.11 and php 5.3.1, both are good. So have it, use it and enjoy it.

If you have problems, join our QQ Group or Google Group. Want more? Vist [[http://solarphp.cn/][http://solarphp.cn]]

Roy Gu
[[../][http://roygu.com]]
2010-06-24


Update List
===========
All files are utf-8 coded, so if you have some trouble to view codes, change a more powerful tool, just like editplus.

[1] different separator
@ /script/solar [Update]
# line 114
different path\_separator between windows(;) and linux(:)
-
* use PATH\_SEPARATOR replace ":"
-----
# line 64
different directory\_separator between windows(\) and linux(/)
-
* use "\\" or "\" instead of "/"

[2] windows does not support posix\_isatty
@ /source/solar/Solar/Vt100.php [Update]
# line 140
windows doesn't support TTY(posix\_isatty)
-
* made a if-condition first

[3] fix path separator, if on windows, "\" will replace "/"
@ /source/solar/Solar/Dir.php [Update]
# line 100
-
* add function fixSeparator to make right path separator

[4] separator and parameters in symlink command
@ /source/solar/Solar/Symlink.php [Update]
# line 83
in cli of windows , you shoud use "\" instead of "/"
-
*fix separator if on windows, "\" will replace "/"
-----
# line 98 and 103
wrong command format
-
*mklink [[/D] | [/H] | [/J]] link target

[5] link vendor
@ /source/solar/Solar/Cli/LinkVendor.php [Update]
# line 109 and 116
create /script/vendor.bat, if the vendor is solar , create links for it in include path.
-----
# line 145
wrong message tips,if exec("mklink tgt src") success, it returns
"symbolic link created for foo.php <<===>> bar.php"
-
* change it to "complete".

[6] mysql charset
@ /source/solar/Solar/Sql/Adapter/Mysql.php [Update]
# line 127
in config file, you shoud have a 'charset'=>'utf8' key-value pair

* override father's \_postConnection function

[7] SCW(Solar CLI for Windows)
@ /script/solar.bat [Add]
Now, you can use solar cli same as on linux
-----
@ /script/phpenv.ini [Add]
a config file, tell where is the php.exe and php.ini


How to Use SCW(Solar CLI for Windows)
======================================
Actually, you can do even more than on linux.
[1] config
please modify phpenv.ini under /script dir to config the php envirenment variables.
where:
PHP\_EXE represents the path of the php.exe;
PHP\_INI represents the path of the php.ini(the one apache use);

After that, let's have a test.
open CMD, switch to solar dir and then type(symbol "#" is just a DOS prompt):
# script\solar -v

you will get:
Solar CLI for Windows(SCW for short) 1.0.
Copyright (c) 2010 Roy Gu - Usions, Inc.

See it? Congratulations.

[2] link Solar vendor(if you are under linux, you needn't do this step)
type:
# script\solar link-vendor Solar

switch to /include dir, you will see:
# dir

Directory of D:\xampp\htdocs\solarlatest\include

2010-06-24 22:05 <DIR> .
2010-06-24 22:05 <DIR> ..
2010-06-24 22:05 <SYMLINKD> Acme [..\source\acme\Acme]
2010-06-24 22:05 <DIR> Fixture
2010-06-24 22:05 <DIR> Mock
2010-06-24 20:30 <SYMLINKD> Solar [..\source\solar\Solar]
2010-06-24 20:30 <SYMLINK> Solar.php [..\source\solar\Solar.php]
2010-06-24 22:05 <DIR> Test

Yes, if you see these SYMLINKs, you are close.

[3] do everything as normal
Such as:
type:
# script\solar make-vendor Acme

[4] even more
solar
-h help infomation
-v show version
-phpv get php version
make-vendor make vendor
link-vendor link vendor
make-app make application
make-model make model


